########################################################################################################################
#                                        Ingest configuration file template                                            #
########################################################################################################################
### Zenodo resources
#
## path to YML file with definitions of splice sites. Try this first:
# https://zenodo.org/record/6395954/files/splicing-information-content-matrix.yaml?download=1
splicingInformationContentMatrix:

## path to TSV file with ESRSeq (hexamer) scores. Try this first:
# https://zenodo.org/record/6395954/files/hexamer-scores.tsv?download=1
hexamerTsvPath:

## path to TSV file with SMS (septamer) scores. Try this first:
# https://zenodo.org/record/6395954/files/septamer-scores.tsv?download=1
septamerTsvPath:

classifiers:
  # a list of classifiers to ingest
  # an unique version ID, e.g. `v1`
  # Try these first:
  #  https://zenodo.org/record/6395954/files/ensemble.lr.rf.v0.4.4.yaml?download=1
  #  https://zenodo.org/record/6395954/files/ensemble.lr.rf.v0.4.6.yaml?download=1
  - version:
    # path to YML file with classifier data
    classifierPath:

### Public resources
#
## URL of Jannovar v0.35 RefSeq cache. Try these first:
#  hg19 - https://storage.googleapis.com/ielis/jannovar/hg19_refseq.ser
#  hg38 - https://storage.googleapis.com/ielis/jannovar/hg38_refseq.ser
refseqUrl:

## URL of Jannovar v0.35 Ensembl cache. Try these first:
#  hg19 - https://storage.googleapis.com/ielis/jannovar/hg19_ensembl.ser
#  hg38 - https://storage.googleapis.com/ielis/jannovar/hg38_ensembl.ser
ensemblUrl:

## URL of Jannovar v0.35 UCSC cache. Try these first:
#  hg19 - https://storage.googleapis.com/ielis/jannovar/hg19_ucsc.ser
#  hg38 - https://storage.googleapis.com/ielis/jannovar/hg38_ucsc.ser
ucscUrl:

## we expect to find tarball with FASTA files per-chromosome here
#hg19 - http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz
#hg38 - http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chromFa.tar.gz
fastaUrl:

## NCBI's assembly report
#hg19 - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_assembly_report.txt
#hg38 - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_assembly_report.txt
assemblyReportUrl:

## BigWig file with genome-wide PhyloP scores
#hg19 - http://hgdownload.cse.ucsc.edu/goldenpath/hg19/phyloP100way/hg19.100way.phyloP100way.bw
#hg38 - http://hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP100way/hg38.phyloP100way.bw
phylopUrl:
