# Ingest configuration file template
  # path to YML file with definitions of splice sites
squirls.ingest:
  splicing-information-content-matrix:
  # path to directory with serialized Jannovar cache files with `*.ser` suffix
  jannovar-transcript-db-dir:
  # path to TSV file with ESRSeq (hexamer) scores
  hexamer-tsv-path:
  # path to TSV file with SMS (septamer) scores
  septamer-tsv-path:
  classifiers:
    # a list of classifiers to ingest
    # an unique version ID, e.g. `v1`
    - version:
      # path to YML file with classifier data
      classifierPath:
  # we expect to find tarball with FASTA files per-chromosome here
  fasta-url:
  #hg19: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz
  #hg38: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chromFa.tar.gz
  assembly-report-url:
  #hg19: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_assembly_report.txt
  #hg38: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_assembly_report.txt
  phylop-url:
  #hg19: http://hgdownload.cse.ucsc.edu/goldenpath/hg19/phyloP100way/hg19.100way.phyloP100way.bw
  #hg38: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/phyloP100way/hg38.phyloP100way.bw


# Do not edit anything below
spring:
  flyway:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
